name: golint

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go 3.9
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3

      - name: Set up Golang-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0
          
      - name: Run Golang-lint
        run: |
          golangci-lint run
